### PR TITLE
Fixing syntax error in readme

### PR DESCRIPTION
**Pull request by stefanjudis**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Although the IPR check fails, it's fine to merge this. I spotted the same issue in my PR.

**Comment by stefanjudis** [comment]
@marcoscaceres How do I fix this IPR thing?. I tried it, but was not able to resolve it...

**Comment by marcoscaceres** [comment]
@stefanjudis, it should work if you join the group? https://www.w3.org/community/wicg/participants

**Comment by marcoscaceres** [comment]
@stefanjudis, it should be good now for contributions. Got indication you signed IPR agreement. Unfortunately, this system doesn't auto update the PR.

**Comment by marcoscaceres** [comment]
(Will merge tomorrow to avoid you having to go through any more pain)

**Comment by stefanjudis** [comment]
@marcoscaceres Thanks. :)

**Pull request merged**
